-- --------------------------------------------------
-- ------------------ FOREIGN KEYS ------------------
ALTER TABLE `ARMOR` 
ADD CONSTRAINT fk_ARMOR_RECIPE
FOREIGN KEY (`RecipeID`)
REFERENCES `RECIPE`(`RecipeID`);

ALTER TABLE `WEAPON` 
ADD CONSTRAINT fk_WEAPON_RECIPE
FOREIGN KEY (`RecipeID`)
REFERENCES `RECIPE`(`RecipeID`);

ALTER TABLE `RECIPE` 
ADD CONSTRAINT fk_RECIPE_MATERIAL
FOREIGN KEY (`Material1`)
REFERENCES `Material`(`MaterialID`);

ALTER TABLE `RECIPE` 
ADD CONSTRAINT fk_RECIPE_MATERIAL2
FOREIGN KEY (`Material2`)
REFERENCES `Material`(`MaterialID`);

ALTER TABLE `RECIPE` 
ADD CONSTRAINT fk_RECIPE_MATERIAL3
FOREIGN KEY (`Material3`)
REFERENCES `Material`(`MaterialID`);

ALTER TABLE `RECIPE` 
ADD CONSTRAINT fk_RECIPE_MATERIAL4
FOREIGN KEY (`Material4`)
REFERENCES `Material`(`MaterialID`);

ALTER TABLE `RECIPE` 
ADD CONSTRAINT fk_RECIPE_MATERIAL5
FOREIGN KEY (`Material5`)
REFERENCES `Material`(`MaterialID`);

ALTER TABLE `RECIPE` 
ADD CONSTRAINT fk_RECIPE_MATERIAL6
FOREIGN KEY (`Material6`)
REFERENCES `Material`(`MaterialID`);

ALTER TABLE `RECIPE` 
ADD CONSTRAINT fk_RECIPE_MATERIAL7
FOREIGN KEY (`Material7`)
REFERENCES `Material`(`MaterialID`);

ALTER TABLE `RECIPE` 
ADD CONSTRAINT fk_RECIPE_MATERIAL8
FOREIGN KEY (`Material8`)
REFERENCES `Material`(`MaterialID`);

ALTER TABLE `RECIPE` 
ADD CONSTRAINT fk_RECIPE_MATERIAL9
FOREIGN KEY (`Material9`)
REFERENCES `Material`(`MaterialID`);

-- ALTER TABLE `STATS` 
-- ADD CONSTRAINT fk_STATS_MOB
-- FOREIGN KEY (`MOBID`)
-- REFERENCES `MOB`(`NamingID`);

-- ALTER TABLE `STATS` 
-- ADD CONSTRAINT fk_STATS_ECTWEAP
-- FOREIGN KEY (`ENCHANTED_WEAPON_ID`)
-- REFERENCES `WEAPON`(`WeaponID`);

-- ALTER TABLE `STATS` 
-- ADD CONSTRAINT fk_STATS_POTION
-- FOREIGN KEY (`POTION_ID`)
-- REFERENCES `POTION`(`Potion_id`);

-- ALTER TABLE `STATS` 
-- ADD CONSTRAINT fk_STATS_ECTHEML
-- FOREIGN KEY (`ENCHANTED HEMLET ID`)
-- REFERENCES `ARMOR`(`NamingID`);

-- ALTER TABLE `STATS` 
-- ADD CONSTRAINT fk_STATS_ECTCHEST
-- FOREIGN KEY (`ENCHANTED CHESTPLATE ID`)
-- REFERENCES `ARMOR`(`NamingID`);

-- ALTER TABLE `STATS` 
-- ADD CONSTRAINT fk_STATS_ECTHLEG
-- FOREIGN KEY (`ENCHANTED LEGGINGS ID`)
-- REFERENCES `ARMOR`(`NamingID`);

-- ALTER TABLE `STATS` 
-- ADD CONSTRAINT fk_STATS_ECTHBOOTS
-- FOREIGN KEY (`ENCHANTED BOOTS ID`)
-- REFERENCES `ARMOR`(`NamingID`);

ALTER TABLE `ARMOR ENCHANTED` 
ADD CONSTRAINT fk_ARMOR
FOREIGN KEY (`ARMOR_ID`)
REFERENCES `ARMOR`(`NamingID`);

ALTER TABLE `ARMOR ENCHANTED` 
ADD CONSTRAINT fk_ARMOR_ENCHT
FOREIGN KEY (`ENCHANTMENT_id`)
REFERENCES `ENCHANTMENTS`(`ENCHANTMENT_ID`);

ALTER TABLE `WEAPON ENCHANTED` 
ADD CONSTRAINT fk_WEAPON
FOREIGN KEY (`WEAPON_ID`)
REFERENCES `WEAPON`(`WeaponID`);

ALTER TABLE `WEAPON ENCHANTED` 
ADD CONSTRAINT fk_WEAPON_ENCHT
FOREIGN KEY (`ENCHANTED_WEAPON_ID`)
REFERENCES `ENCHANTMENTS`(`ENCHANTMENT_ID`);